package com.iws_manager.iws_manager_api.repositories;

import com.iws_manager.iws_manager_api.models.Order;
import com.iws_manager.iws_manager_api.models.Employee;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.stereotype.Repository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

@Repository
public interface OrderRepository extends JpaRepository<Order, Long> {

    @EntityGraph(attributePaths = {
        "approvalStatus",
        "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram",
        "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state",
        "contractStatus",
        "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state",
        "employeeIws", "employeeIws.teamIws", "employeeIws.user",
        "fundingProgram",
        "orderType",
        "project", "project.customer", "project.fundingProgram", "project.promoter",
        "promoter", "promoter.country"
    })
    List<Order> findAll();

   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findAllByOrderByOrderTitleAsc();

    @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findAllByOrderByOrderLabelAsc();

   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByCustomerIdOrderByOrderTitleAsc(Long customerId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByCustomerIdOrderByOrderLabelAsc(Long customerId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByCustomerIdOrderByOrderNoAsc(Long customerId);

    //PROPERTIES
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByAcronym(String acronym);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByApprovalDate(LocalDate approvalDate);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByApprovalStatusId(Long approvalStatusId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByBasiccontractId(Long basiccontractId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByContractData1(String contractData1);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByContractData2(String contractData2);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByContractorId(Long contractorId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByContractStatusId(Long contractStatusId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByCustomerId(Long customerId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByEmployeeIwsId(Long employeeIwsId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByFixCommission(BigDecimal fixCommission);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByFundingProgramId(Long fundingProgramId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByIwsProvision(BigDecimal iwsProvision);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByMaxCommission(BigDecimal maxCommission);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByNextDeptDate(LocalDate nextDeptDate);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByNoOfDepts(Integer noOfDepts);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderDate(LocalDate orderDate);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderLabel(String orderLabel);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderNo(Integer orderNo);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderTypeId(Long orderTypeId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderTitle(String orderTitle);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderValue(BigDecimal orderValue);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByProjectId(Long projectId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByPromoterId(Long promoterId);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findBySignatureDate(LocalDate signatureDate);

    //HELPERS
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderValueLessThanEqual(BigDecimal value);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderValueGreaterThanEqual(BigDecimal value);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByOrderValueBetween(BigDecimal startValue, BigDecimal endValue);

   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByApprovalDateBetween(LocalDate start, LocalDate end);
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByApprovalDateIsNull();
   @EntityGraph(attributePaths = {"approvalStatus", "basiccontract", "basiccontract.contractStatus", "basiccontract.customer", "basiccontract.customer.branch", "basiccontract.customer.companytype", "basiccontract.customer.country", "basiccontract.customer.state", "basiccontract.employeeIws", "basiccontract.fundingProgram", "contractor", "contractor.country", "contractor.customer", "contractor.customer.branch", "contractor.customer.companytype", "contractor.customer.country", "contractor.customer.state", "contractStatus", "customer", "customer.branch", "customer.companytype", "customer.country", "customer.state", "employeeIws", "employeeIws.teamIws", "employeeIws.user", "fundingProgram", "orderType", "project", "project.customer", "project.fundingProgram", "project.promoter", "promoter", "promoter.country"})
    List<Order> findByApprovalDateIsNotNull();

    // get employees by project id through a specific customer id
    @Query("""
        select distinct e
        from Order o
        join o.customer c
        join Employee e on e.customer = c
        where o.project.id = :projectId
        order by e.firstname asc
    """)
    List<Employee> findEmployeesByProjectIdOrderByFirstnameAsc(@Param("projectId") Long projectId);
}
